[Ascend950][BugFix] fix npu_add_rms_norm_dynamic_quant error in A5 (#9334)
### What this PR does / why we need it?
**Error information**
RuntimeError: npu_add rms norm_dynamic_quant:../third party/op-plugin/
AcINN_Parameter_Error(EZ1001): Input tensor's shape[[1]] should be same
with output's shape[[39500, 5120]].
**Error Cause**
`output_mask` Input parameters do not meet operator requirements
**Solution**
[Operator
Documentation](https://gitcode.com/cann/ops-nn/blob/master/norm/add_rms_norm_dynamic_quant/docs/aclnnAddRmsNormDynamicQuantV2.md)
Modify to `[True, False]`

### Does this PR introduce _any_ user-facing change?
no
### How was this patch tested?

- vLLM version: v0.20.2
- vLLM main:
https://github.com/vllm-project/vllm/commit/0d4d334eaa583b9c09aa4eb7538c22db99fd84b3

Signed-off-by: wangkunpeng <1289706727@qq.com>