Revert "[Refactor][Test] Simplify MC2 capacity and MoE comm selection" (#11415)
This reverts commit aabec5efb082c960ca54ac9006e1780f0057378e.

break CI:
```
  FAILED tests/ut/test_ascend_forward_context.py::test_set_mc2_tokens_capacity_without_cudagraph_caps_at_512_and_aligns - RuntimeError: Ascend config is not initialized. Please call init_ascend_config first.
  FAILED tests/ut/test_ascend_forward_context.py::test_set_mc2_tokens_capacity_with_cudagraph_uses_capture_size_and_aligns - RuntimeError: Ascend config is not initialized. Please call init_ascend_config first.
```


https://github.com/vllm-project/vllm-ascend/actions/runs/28650206637/job/84967064018?pr=10935#step:20:3502
- fix lint
- fix mock vllm-config in ut of platform

- vLLM version: v0.23.0
- vLLM main:
https://github.com/vllm-project/vllm/commit/a30addc7548a9a8b9b3323a7bc3eb7d7c4895d1c

---------

Signed-off-by: MrZ20 <2609716663@qq.com>
Signed-off-by: MengqingCao <cmq0113@163.com>
Signed-off-by: Mrz20 <2609716663@qq.com>
Co-authored-by: MengqingCao <cmq0113@163.com>